import { WatchFace } from '../types';

/**
 * Generates official Google Watch Face Format (WFF) XML compliant with Wear OS 4 & 5.
 */
export function generateWffXml(watchFace: WatchFace): string {
  const width = 450;
  const height = 450;
  const cx = width / 2;
  const cy = height / 2;

  const complicationXml = watchFace.complications
    .filter((c) => c.type !== 'none')
    .map((c, index) => {
      let slotX = cx;
      let slotY = cy;
      const size = 70;

      if (c.slot === 'top') {
        slotX = cx - size / 2;
        slotY = 60;
      } else if (c.slot === 'bottom') {
        slotX = cx - size / 2;
        slotY = height - 60 - size;
      } else if (c.slot === 'left') {
        slotX = 60;
        slotY = cy - size / 2;
      } else if (c.slot === 'right') {
        slotX = width - 60 - size;
        slotY = cy - size / 2;
      } else if (c.slot === 'center') {
        slotX = cx - size / 2;
        slotY = cy + 40;
      }

      const complicationTypesMap: Record<string, string> = {
        battery: 'RANGED_VALUE, SHORT_TEXT',
        steps: 'RANGED_VALUE, GOAL_PROGRESS',
        heart_rate: 'SHORT_TEXT, ICON',
        weather: 'SHORT_TEXT, ICON, SMALL_IMAGE',
        calendar: 'SHORT_TEXT, LONG_TEXT',
        uv: 'RANGED_VALUE, SHORT_TEXT',
        sunset: 'SHORT_TEXT, ICON',
        compass: 'ICON, SHORT_TEXT',
        media: 'CUSTOM, ICON',
        world_clock: 'SHORT_TEXT',
      };

      const supportedTypes = complicationTypesMap[c.type] || 'SHORT_TEXT';

      return `      <!-- Complication Slot: ${c.slot.toUpperCase()} (${c.type}) -->
      <ComplicationSlot
          slotId="${index + 1}"
          supportedTypes="${supportedTypes}"
          x="${Math.round(slotX)}"
          y="${Math.round(slotY)}"
          width="${size}"
          height="${size}">
        <DefaultProviderPolicy
            defaultSystemProviderType="${c.type.toUpperCase()}"
            defaultSystemProvider="${c.type}" />
        <Complication color="${watchFace.colors.primary}">
          <PartText
              x="0"
              y="0"
              width="${size}"
              height="${size}"
              color="${watchFace.colors.primary}"
              fontFamily="${watchFace.dial.hourMarkerFont}">
            <Template>%s</Template>
          </PartText>
        </Complication>
      </ComplicationSlot>`;
    })
    .join('\n');

  let clockElementsXml = '';

  if (watchFace.type === 'analog' || watchFace.type === 'hybrid') {
    const sweep = watchFace.hands.sweepSeconds ? 'SWEEP' : 'STEP';
    clockElementsXml += `      <!-- Analog Clock Hands (WFF Standard) -->
      <AnalogClock x="0" y="0" width="${width}" height="${height}">
        <!-- Hour Hand -->
        <HourHand
            x="${cx - 8}"
            y="70"
            width="16"
            height="${cy - 70}"
            pivotX="0.5"
            pivotY="1.0"
            color="${watchFace.colors.hands}">
          <Variant mode="AMBIENT" color="#FFFFFF" />
        </HourHand>

        <!-- Minute Hand -->
        <MinuteHand
            x="${cx - 5}"
            y="40"
            width="10"
            height="${cy - 40}"
            pivotX="0.5"
            pivotY="1.0"
            color="${watchFace.colors.primary}">
          <Variant mode="AMBIENT" color="#CCCCCC" />
        </MinuteHand>

        ${
          watchFace.hands.showSeconds
            ? `<!-- Second Hand -->
        <SecondHand
            x="${cx - 2}"
            y="25"
            width="4"
            height="${cy - 10}"
            pivotX="0.5"
            pivotY="0.9"
            movementType="${sweep}"
            color="${watchFace.colors.accent}">
          <Variant mode="AMBIENT" alpha="0" />
        </SecondHand>`
            : ''
        }

        <!-- Center Cap -->
        <PartDraw x="${cx - 7}" y="${cy - 7}" width="14" height="14">
          <Circle cx="7" cy="7" radius="6" color="${watchFace.colors.accent}" />
        </PartDraw>
      </AnalogClock>`;
  }

  if (watchFace.type === 'digital' || watchFace.type === 'hybrid') {
    const isStacked = watchFace.digital.layout === 'stacked';
    clockElementsXml += `\n      <!-- Digital Time Component (WFF) -->
      <DigitalClock x="0" y="${isStacked ? 110 : 170}" width="${width}" height="120">
        <TimeText
            format="${watchFace.digital.format24h ? 'HH:mm' : 'hh:mm'}"
            color="${watchFace.colors.primary}"
            fontFamily="${watchFace.digital.font}"
            size="${isStacked ? 64 : 52}"
            alignment="CENTER">
          <Variant mode="AMBIENT" color="#FFFFFF" />
        </TimeText>
      </DigitalClock>`;
  }

  return `<?xml version="1.0" encoding="utf-8"?>
<!-- 
  Google Pixel Watch - Watch Face Format (WFF)
  Target: Wear OS 4 / Wear OS 5 / Android 15
  Generated by Pixel Watch Face Studio
  Format Spec: https://developer.android.com/training/wearables/wff
-->
<WatchFace
    xmlns="http://schemas.android.com/wear/watchface"
    width="${width}"
    height="${height}"
    clipShape="CIRCLE">

  <Metadata>
    <Property name="id" value="${watchFace.id}" />
    <Property name="title" value="${watchFace.name}" />
    <Property name="category" value="${watchFace.category}" />
    <Property name="preview" value="preview.png" />
    <Property name="batteryEfficiency" value="${watchFace.batteryEfficiency}" />
    <Property name="wffVersion" value="1.0" />
  </Metadata>

  <!-- User Customizable Styles (Dynamic Color & Material You) -->
  <UserConfigurations>
    <ColorConfiguration id="primary_theme" defaultValue="${watchFace.colors.primary}">
      <ColorOption id="dynamic_system" color="${watchFace.colors.primary}" />
      <ColorOption id="secondary_accent" color="${watchFace.colors.secondary}" />
      <ColorOption id="tertiary_tone" color="${watchFace.colors.tertiary}" />
    </ColorConfiguration>
    <BooleanConfiguration id="show_seconds" defaultValue="${watchFace.hands.showSeconds}" />
    <ListConfiguration id="dial_style" defaultValue="${watchFace.dial.style}">
      <ListOption id="ticks" />
      <ListOption id="dots" />
      <ListOption id="concentric" />
      <ListOption id="clean" />
    </ListConfiguration>
  </UserConfigurations>

  <!-- Main Scene Definition -->
  <Scene backgroundColor="${watchFace.colors.background}">

    <!-- Background Layer with Ambient Power Optimization -->
    <PartDraw x="0" y="0" width="${width}" height="${height}">
      <Circle cx="${cx}" cy="${cy}" radius="${cx - 2}" color="${watchFace.colors.dialBg}" />
      <Variant mode="AMBIENT" alpha="0.15" />
    </PartDraw>

    <!-- Dial Ticks & Markers -->
    <PartDraw x="0" y="0" width="${width}" height="${height}">
      <!-- Dial Geometry: ${watchFace.dial.style} (${watchFace.dial.ticksCount} ticks) -->
      <Ring
          cx="${cx}"
          cy="${cy}"
          innerRadius="${cx - 18}"
          outerRadius="${cx - 15}"
          color="${watchFace.colors.secondary}"
          alpha="${watchFace.dial.dialRingOpacity}" />
    </PartDraw>

${complicationXml}

${clockElementsXml}

  </Scene>
</WatchFace>`;
}

export function downloadWffXmlFile(watchFace: WatchFace) {
  const xmlContent = generateWffXml(watchFace);
  const blob = new Blob([xmlContent], { type: 'application/xml;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `watchface_${watchFace.id}.xml`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function generateManifestJson(watchFace: WatchFace): string {
  return JSON.stringify(
    {
      packageName: `com.google.android.wearable.watchface.${watchFace.id.replace(/-/g, '_')}`,
      versionCode: 100,
      versionName: '1.0.0',
      minWearOsVersion: 4,
      targetWearOsVersion: 5,
      watchFaceFormatVersion: '1.0',
      permissions: ['android.permission.WAKE_LOCK', 'com.google.android.wearable.permission.RECEIVE_COMPLICATION_DATA'],
      watchFaceConfig: {
        id: watchFace.id,
        name: watchFace.name,
        nameAr: watchFace.nameAr,
        category: watchFace.category,
        type: watchFace.type,
        colors: watchFace.colors,
        batteryGrade: watchFace.batteryEfficiency,
      },
    },
    null,
    2
  );
}
